### ISSUE TITLE
Adding styles to sites with strict CSP

### ISSUE THREAD

**Issue by deevroman** [erosman/firemonkey#12]
I'm trying to add to the site openstreetmap.org new styles using the following script:

```js
// ==UserScript==
// @name         Test JS
// @match        https://www.openstreetmap.org/*
// @grant        GM_addElement
// @inject-into  content
// @version      1.0
// ==/UserScript==

console.log("begin");

GM_addElement(document.head, "style", {
  textContent: `
  * {
    background: red !important;
  }
  `,
});

console.log("end");
```

This works in TM and VM, but doesn't work in FM. I've heard that TM relaxes page CSP, but what about VM? Does it relax CSP too?

---

I also noticed that FireMonkey allows to add custom styles to the page, and they are successfully applied on openstreetmap.org. And this suggests that in theory, userscripts could have a similar API. For example, GM_addStyle could use it, and not just be a wrapper over GM_addElement. Are there any obstacles to this?

**Comment by erosman** [comment]
> I've heard that TM relaxes page CSP,...

That is correct.

> but what about VM? Does it relax CSP too?

AFAIK, it was rejected. _(see FM Help -> alter page CSP)_
VM by default injects into `page` context and loads its API into every page.
That may be the reason.


FM injects userCSS using a CSS injection API which doesn’t conflict with page's CSP for JavaScript injection. e.g.

```css
/* 
==UserCSS==
@name         Test CSS
@match        https://www.openstreetmap.org/*
@version      1.0
==/UserCSS==
*/

* {
  background: red !important;
}
```

**Comment by Atheonioo** [comment]
Hi, I am trying to add downloadable fonts, they do not connect anywhere, they are base64 encoded; first I tried injecting the css to the page and with unsafewindow, so I tried to relax the csp with this script:
```
// ==UserScript==
// @name        Relax CSP for base64
// @match       https://github.com/*
// @grant       GM.webRequest
// @run-at      document-start
// ==/UserScript==

GM.webRequest.onHeadersReceived.addListener(
  (details) => {
    const headers = details.responseHeaders;
    const cspHeader = headers.find(header => header.name.toLowerCase() === 'content-security-policy');

    if (cspHeader) {
      cspHeader.value = cspHeader.value.replace(
        /font-src[^;]*;/i,
        "font-src 'self' data:;"
      );
    }

    return { responseHeaders: headers };
  },
  { urls: ["<all_urls>"] },
  ["blocking", "responseHeaders"]
);
```
`GM.webRequest` is not specified in the wiki if it is supported or not anyway it didn't work, I also tried with `document.querySelector('meta[http-equiv="Content-Security-Policy"]')?.remove();` but same result, so I assume it is not possible to interact with the csp in FM. The only way I have managed to get it to work is by modifying the header but I want to leave it as a last alternative.

**Comment by erosman** [comment]
> `GM.webRequest` is not specified in the wiki if it is supported or not anyway it didn't work

That is not supported.
Userscripts are content scripts while `webRequest` happens before tab content is loaded.

> [Add-on Policies](https://extensionworkshop.com/documentation/publish/add-on-policies/#development-practices)
> - Add-ons must not relax web page security headers, such as the Content Security Policy.

See also:
-  [Add support to webRequest API](https://github.com/violentmonkey/violentmonkey/issues/583)

**Comment by Atheonioo** [comment]
I see... So there is no way to add downloadable typefaces?

**Comment by erosman** [comment]
> I see... So there is no way to add downloadable typefaces?

What are yo trying to do?
- Download font from the site?
- Inject a font into the site?

**Comment by Atheonioo** [comment]
Inject a font into the site.
They are coded based64 so they don't even connect to a site. 

BTW, I try to inject the fonts from TM using GM_addElement in Edge and Firefox; In Edge they were injected without any inconvenience but in Firefox they are not injected, so if it does not even work on TM, I do not think that FM is the exepection, But I don't lose anything with asking.

**Comment by erosman** [comment]
Look at the Help under CSS `@require` and `@import`.
I tested it now on Github and any of these works fine.

 ```css
/*
==UserCSS==
@name          0 CSS require import
@description   FireMonkey test script
@match         https://github.com/*
@require       https://fonts.googleapis.com/css?family=Tangerine
==/UserCSS==
*/

:root {
  --color: green;
 }

 body {
   border: 1px solid var(--color);
   color: var(--color);
   font-family: 'Tangerine', serif;
 }
 ```

 ```css
/*
==UserCSS==
@name          0 CSS require import
@description   FireMonkey test script
@match         https://github.com/*
==/UserCSS==
*/

@import url('https://fonts.googleapis.com/css?family=Tangerine');

:root {
  --color: green;
 }

 body {
   border: 1px solid var(--color);
   color: var(--color);
   font-family: 'Tangerine', serif;
 }
 ```

 ```css
/*
==UserCSS==
@name          0 CSS require import
@description   FireMonkey test script
@match         https://github.com/*
==/UserCSS==
*/

@import 'https://fonts.googleapis.com/css?family=Tangerine';

:root {
  --color: green;
 }

 body {
   border: 1px solid var(--color);
   color: var(--color);
   font-family: 'Tangerine', serif;
 }
 ```
