### ISSUE TITLE
CSS grid syntax considered as invalid when it isn't

### ISSUE THREAD

**Issue by qwertychouskie** [erosman/firemonkey#19]
The following user style is considered invalid:
```css
/*
==UserCSS==
@name             Discord CSS
@match            https://discord.com/channels/*
@version          1.0
==/UserCSS==
*/

.visual-refresh .base_c48ade {
  grid-template-rows: [top] 0 [titleBarEnd] min-content [noticeEnd] 1fr [contentEnd] min-content [end];
}
```

What's even weirder is that with `@match            *://*/*` the style is considered valid:
```css
/*
==UserCSS==
@name             Discord CSS
@match            *://*/*
@version          1.0
==/UserCSS==
*/

.visual-refresh .base_c48ade {
  grid-template-rows: [top] 0 [titleBarEnd] min-content [noticeEnd] 1fr [contentEnd] min-content [end];
}
```
I suspect in the latter case, the presence of `*/` in the `@match` is throwing off the validator.
